export const START_IMAGE_FETCHING = "START_IMAGE_FETCHING";
export const SUCCESS_IMAGE_FETCHING = "SUCCESS_IMAGE_FETCHING";
export const FAILED_IMAGE_FETCHING = "FAILED_IMAGE_FETCHING";

export const TOGGLE_IMAGE_SELECT = "TOGGLE_IMAGE_SELECT";
export const TOGGLE_IMAGE_GRID = "TOGGLE_IMAGE_GRID";

export const START_GRID_FETCHING = "START_GRID_FETCHING";
export const SUCCESS_GRID_FETCHING = "SUCCESS_GRID_FETCHING";
export const FAILED_GRID_FETCHING = "SUCCESS_GRID_FETCHING";

export const USER_EXIST = "USER_EXIST";

export const START_GRID_SAVING = "START_GRID_SAVING";
export const SUCCESS_GRID_SAVING = "SUCCESS_GRID_SAVING";
export const FAILED_GRID_SAVING = "FAILED_GRID_SAVING";

export const EDIT_GRID = "EDIT_GRID";
